MACOSX_SDK_VERSION:    # [osx and x86_64]
  - 10.15              # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:   # [osx and x86_64]
  - 10.15                   # [osx and x86_64]
c_compiler_version:     # [linux]
  - '10'                # [linux]
cxx_compiler_version:   # [linux]
  - '10'                # [linux]