{% set name = "pymongoarrow" %}
{% set version = "0.6.2" %}
{% set llvm_version = "14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymongoarrow/pymongoarrow-{{ version }}.tar.gz
  sha256: 28d0d2b15a72b612c6533bed2a55d847b8b11500035f595ae7036f36d9f10c3c

build:
  number: 0
  skip: true  # [arrow_cpp == "6.0.2"]
  script:
    - export MONGO_NO_COPY_LIBARROW=1             # [unix]
    - export MONGO_LIBARROW_DIR="${PREFIX}/lib"   # [unix]
    - export MONGO_NO_COPY_LIBBSON=1              # [unix]
    - export LIBBSON_INSTALL_DIR="${PREFIX}"      # [unix]
    - set MONGO_NO_COPY_LIBARROW=1                # [win]
    - set "MONGO_LIBARROW_DIR=%LIBRARY_LIB%"      # [win]
    - set MONGO_NO_COPY_LIBBSON=1                 # [win]
    - set "LIBBSON_INSTALL_DIR=%LIBRARY_PREFIX%"  # [win]
    - MACOS_DEPLOYMENT_TARGET="10.15" {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - pyarrow                                # [build_platform != target_platform]
    - libbson                                # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - clangdev {{ llvm_version }}            # [osx and arm64]
    - llvmdev {{ llvm_version }}             # [osx and arm64]
    - gnuconfig                              # [osx and arm64]
    - setuptools >=47
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - {{ pin_compatible('arrow-cpp', exact=True) }}
    - clangdev {{ llvm_version }}
    - llvmdev {{ llvm_version }}
    - cython >=0.29
    - libbson >=1,<2
    - pip
    - pyarrow >=7
    - pkg-config

  run:
    - {{ pin_compatible('arrow-cpp', exact=True) }}
    - pyarrow >=7
    - pymongo >=3.11,<5
    - python

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  imports:
    - pymongoarrow
  requires:
    - pip
    - pandas
    - numpy
    - pyarrow
    - mongodb     # [not win]
  commands:
    - bash run_the_tests.sh  # [unix and not (ppc64le or python_impl=='pypy')]

about:
  home: https://pypi.org/project/pymongoarrow/
  summary: Tools for using NumPy, Pandas and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - ShaneHarvey
