{% set name = "pymongoarrow" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymongoarrow/pymongoarrow-{{ version }}.tar.gz
  sha256: af9769212eff79cb061673205b9989dcdc7308baa17a5682331a193b76ed0825

build:
  number: 1
  script:
    - export MONGO_NO_COPY_LIBARROW=1             # [unix]
    - export MONGO_LIBARROW_DIR="${PREFIX}/lib"   # [unix]
    - export MONGO_NO_COPY_LIBBSON=1              # [unix]
    - export LIBBSON_INSTALL_DIR="${PREFIX}"      # [unix]
    - set MONGO_NO_COPY_LIBARROW=1                # [win]
    - set "MONGO_LIBARROW_DIR=%LIBRARY_LIB%"      # [win]
    - set MONGO_NO_COPY_LIBBSON=1                 # [win]
    - set "LIBBSON_INSTALL_DIR=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython  >=0.29                         # [build_platform != target_platform]
    - arrow-cpp  <9.1,>=9                    # [build_platform != target_platform]
    - pyarrow  <9.1,>=9                      # [build_platform != target_platform]
    - libbson  >=1,<2                        # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - setuptools >=47
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - arrow-cpp <9.1,>=9
    - cython >=0.29
    - libbson >=1,<2
    - pip
    - pyarrow <9.1,>=9
    - pkg-config
    - python

  run:
    - pyarrow <9.1,>=9
    - pymongo >=3.11,<5
    - python

test:
  imports:
    - pymongoarrow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pymongoarrow/
  summary: Tools for using NumPy, Pandas and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - ShaneHarvey
